/*---------------------------------------------------------------------------
 *
 * Created by Dennis Kofflard, dennis@kofflard.com
 * 2015-12-02
 *
 *---------------------------------------------------------------------------
 */


#ifndef I2C_TRIDENT2_H
#define I2C_TRIDENT2_H



#define I2C_TRIDENT2_SWITCH_COUNT 2
#define I2C_TRIDENT2_SWITCH_1_ADDRESS  0xE0
#define I2C_TRIDENT2_SWITCH_2_ADDRESS  0xE2


#define I2C_TRIDENT2_DAS_ADDRESS  0x50


#define I2C_TRIDENT2_GPIO_ADDRESS  0x40
//upper bank is offset by 2 in the pinout,
//  offsetting to allow 0,1,2..6,7,8,9.. numbering
#define I2C_TRIDENT2_GPIO_PORT_BANK2_OFFSET  2
#define I2C_TRIDENT2_GPIO_PORT_I2C_HUB_EN3   (15 - I2C_TRIDENT2_GPIO_PORT_BANK2_OFFSET)
#define I2C_TRIDENT2_GPIO_PORT_I2C_HUB_EN2   (14 - I2C_TRIDENT2_GPIO_PORT_BANK2_OFFSET)
#define I2C_TRIDENT2_GPIO_PORT_I2C_HUB_EN1   (13 - I2C_TRIDENT2_GPIO_PORT_BANK2_OFFSET)
#define I2C_TRIDENT2_GPIO_PORT_SW_BCM_RESET  (12 - I2C_TRIDENT2_GPIO_PORT_BANK2_OFFSET)
#define I2C_TRIDENT2_GPIO_PORT_SW_I2C_RESET  (11 - I2C_TRIDENT2_GPIO_PORT_BANK2_OFFSET)
#define I2C_TRIDENT2_GPIO_PORT_SW_SHDN       (10 - I2C_TRIDENT2_GPIO_PORT_BANK2_OFFSET)



#define I2C_TRIDENT2_EEPROM_ADDRESS  0xAE




//transceiver adress identical for all devices
#define I2C_TRIDENT2_TRANSCEIVER_ADDRESS  0xA0

//transceivers (x11) details
#define I2C_TRIDENT2_TRANSCEIVER_01_SWITCH_DEV  switch1
#define I2C_TRIDENT2_TRANSCEIVER_01_CHANNEL     4
#define I2C_TRIDENT2_TRANSCEIVER_01_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_02_SWITCH_DEV  switch1
#define I2C_TRIDENT2_TRANSCEIVER_02_CHANNEL     5
#define I2C_TRIDENT2_TRANSCEIVER_02_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_03_SWITCH_DEV  switch1
#define I2C_TRIDENT2_TRANSCEIVER_03_CHANNEL     6
#define I2C_TRIDENT2_TRANSCEIVER_03_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_04_SWITCH_DEV  switch1
#define I2C_TRIDENT2_TRANSCEIVER_04_CHANNEL     7
#define I2C_TRIDENT2_TRANSCEIVER_04_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_05_SWITCH_DEV  switch2
#define I2C_TRIDENT2_TRANSCEIVER_05_CHANNEL     0
#define I2C_TRIDENT2_TRANSCEIVER_05_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_06_SWITCH_DEV  switch2
#define I2C_TRIDENT2_TRANSCEIVER_06_CHANNEL     1
#define I2C_TRIDENT2_TRANSCEIVER_06_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_07_SWITCH_DEV  switch2
#define I2C_TRIDENT2_TRANSCEIVER_07_CHANNEL     2
#define I2C_TRIDENT2_TRANSCEIVER_07_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_08_SWITCH_DEV  switch2
#define I2C_TRIDENT2_TRANSCEIVER_08_CHANNEL     3
#define I2C_TRIDENT2_TRANSCEIVER_08_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_09_SWITCH_DEV  switch2
#define I2C_TRIDENT2_TRANSCEIVER_09_CHANNEL     4
#define I2C_TRIDENT2_TRANSCEIVER_09_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_10_SWITCH_DEV  switch2
#define I2C_TRIDENT2_TRANSCEIVER_10_CHANNEL     5
#define I2C_TRIDENT2_TRANSCEIVER_10_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS

#define I2C_TRIDENT2_TRANSCEIVER_11_SWITCH_DEV  switch2
#define I2C_TRIDENT2_TRANSCEIVER_11_CHANNEL     6
#define I2C_TRIDENT2_TRANSCEIVER_11_ADDRESS     I2C_TRIDENT2_TRANSCEIVER_ADDRESS




//PSU's
#define I2C_TRIDENT2_PSU_1V_DIG_SWITCH_DEV  switch1
#define I2C_TRIDENT2_PSU_1V_DIG_CHANNEL     2
#define I2C_TRIDENT2_PSU_1V_DIG_ADDRESS     0xC0

#define I2C_TRIDENT2_PSU_1V_ANLG_SWITCH_DEV  switch1
#define I2C_TRIDENT2_PSU_1V_ANLG_CHANNEL     1
#define I2C_TRIDENT2_PSU_1V_ANLG_ADDRESS     0xC0

#define I2C_TRIDENT2_PSU_3V3_SWITCH_DEV  switch1
#define I2C_TRIDENT2_PSU_3V3_CHANNEL     0
#define I2C_TRIDENT2_PSU_3V3_ADDRESS     0xC2




int trident2_init();
int trident2_init_eeprom();
int trident2_init_gpio();
int trident2_init_transceivers();
int trident2_init_switches();
int trident2_init_das();
int trident2_init_psus();


#endif /* I2C_TRIDENT2_H */



